### ISSUE TITLE
EdgeHub Issue with runtime status backoff and exitcode 128

### ISSUE THREAD

**Issue by vinayr254** [AzureIoTGBB/azure-iot-edge-hol#3]
EdgeAgent is running successfully
Since EdgeHub Issue with runtime status backoff and exitcode 128
not able to proceed 

and even after selecting Edge in Azure Stream Analytics it is reverting back to cloud environment
![capture](https://user-images.githubusercontent.com/24474039/35326612-3bec2f3c-011d-11e8-92db-0d6aa62e8f43.PNG)

**Comment by stevebus** [comment]
fixed over email.  restart of edge solved it.

**Comment by GarthOlivier** [comment]
Restart of edge device in Docker?

**Comment by stevebus** [comment]
restart of edge using the iotedgectl script  (i.e.   "iotedgectl stop" followed by a "iotedgectl start")

**Comment by GarthOlivier** [comment]
Thanks, That's what I thought. It did not resolve my edgeHub backoff state :(

**Comment by stevebus** [comment]
what do your edgeHub and edgeAgent logs say?   (docker logs edgeHub)  and (docker logs edgeAgent)

**Comment by GarthOlivier** [comment]
Seems to be issue in edgeAgent not being able to load files as they are being used by another process
https://github.com/Azure/iot-edge/issues/531

**Comment by stevebus** [comment]
ok - yeah..   I haven't seen that issue crop up where a factory reset of docker wouldn't fix it.  So let's see what the IoT Edge team says.   Just to be sure, you are using Linux containers (on a Windows host), right?  there are known, weird, issues with the labs and Windows containers.

**Comment by GarthOlivier** [comment]
No, using windows containers. 
Maybe this is one of those issues?
I am writing in c# dotnet core 2.0 ... I could switch to Linux

**Comment by stevebus** [comment]
This is not a commentary on all of IoT Edge, but these labs definitely do not work with Windows containers.  Yes, with dot net core 2.0 you can switch to Linux containers. Probably worth a try
